### PR TITLE
Update 2023-04-11-natto.md

### PR DESCRIPTION
**Pull request by daizu27**
fixes to photos in text

### CODE REVIEW

**Comment by daizu27** [comment]
@CamDavidsonPilon minor changes, no idea why jpg is case sensitive

**Comment by daizu27** [comment]
thanks! can you update the live site? hopefully fixes the images

**Comment by CamDavidsonPilon** [comment]
Sorry just seeing this! It was deployed, looks like there was another problem?

**Comment by CamDavidsonPilon** [comment]
Fixed another issue: https://github.com/ControlledMold/ControlledMold.github.io/commit/0a459fe0a5def17a5e3da3c505a85bedd77090e7

Deploying now

**Pull request merged**
